// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBifLJ1RjOTPF0txiXQqvlOo36CTgUbkPo',
    appId: '1:725028337249:web:c429f8058d33a8ad3f1c20',
    messagingSenderId: '725028337249',
    projectId: 'fluid-isotope-198118',
    authDomain: 'fluid-isotope-198118.firebaseapp.com',
    databaseURL: 'https://fluid-isotope-198118.firebaseio.com',
    storageBucket: 'fluid-isotope-198118.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNjtj4U3LHbJAz5jCWuwAXbVqRp5li6zo',
    appId: '1:725028337249:android:dc342ed4109e97193f1c20',
    messagingSenderId: '725028337249',
    projectId: 'fluid-isotope-198118',
    databaseURL: 'https://fluid-isotope-198118.firebaseio.com',
    storageBucket: 'fluid-isotope-198118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB63gnqfn8dIZwksx43OK8xf-9CYUgaTos',
    appId: '1:725028337249:ios:03095c880aa896563f1c20',
    messagingSenderId: '725028337249',
    projectId: 'fluid-isotope-198118',
    databaseURL: 'https://fluid-isotope-198118.firebaseio.com',
    storageBucket: 'fluid-isotope-198118.firebasestorage.app',
    iosBundleId: 'com.example.healthyGoals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB63gnqfn8dIZwksx43OK8xf-9CYUgaTos',
    appId: '1:725028337249:ios:03095c880aa896563f1c20',
    messagingSenderId: '725028337249',
    projectId: 'fluid-isotope-198118',
    databaseURL: 'https://fluid-isotope-198118.firebaseio.com',
    storageBucket: 'fluid-isotope-198118.firebasestorage.app',
    iosBundleId: 'com.example.healthyGoals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBifLJ1RjOTPF0txiXQqvlOo36CTgUbkPo',
    appId: '1:725028337249:web:ba77dc0de95180813f1c20',
    messagingSenderId: '725028337249',
    projectId: 'fluid-isotope-198118',
    authDomain: 'fluid-isotope-198118.firebaseapp.com',
    databaseURL: 'https://fluid-isotope-198118.firebaseio.com',
    storageBucket: 'fluid-isotope-198118.firebasestorage.app',
  );

}